### ISSUE TITLE
Configure NSS DB to use opensc runs when I think it shouldn't

### ISSUE THREAD

**Issue by advocateddrummer** [RedHatOfficial/ansible-rhel7-nist-800-171-cui-role#6]
To whom it may concern, I'm _very_ new to ansible and even newer to NIST 800-171. Please be understanding if I'm making any very stupid mistakes. I'm trying to configure a Linux desktop to run this role and it gets to the "Configure NSS DB to Use opensc" task and fails. 

Perhaps it should be mentioned that we do not intend to use smart cards with this computer/project.

A couple things that I do not understand, on my current system (CentOS Linux release 7.6.1810 (Core)) --- am I safe in assuming that this should run as well on CentOS as RHEL proper? --- the task immediately before this one (Get NSS database smart card configuration) is skipped and I'd sort of assume that the next one should then be skipped as well. Please note:

-  first of all, the _/usr/bin/pkcs11-switch_ application _does not_ exist on this OS.
- second of all, the register created (pkcsw_output) _does not_ have a stdout field

The second bullet above is what is causing the role to fail with the following error:

> TASK [Configure NSS DB To Use opensc] 
> ********************************************************************************************************************
> fatal: [localhost]: FAILED! => {"msg": "The conditional check 'pkcsw_output.stdout != \"opensc\" and
> True' failed. The error was: error while evaluating conditional (pkcsw_output.stdout != \"opensc\" and 
> True): 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/tmp/hiho.yml': line
> 28, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe 
> offending line appears to be:\n\n\n  -   name: Configure NSS DB To Use opensc\n      ^ here\n"}

I also do not understand what's going on in the when clause of the failing task: _when: pkcsw_output.stdout != "opensc" and True_, it would seem to me that this should always run with the _and True_ bit. Am I misunderstanding anything?

I think I've figured out a way to fix this, at least for my use case, I do not know what the correct solution is however. I've replaced the _when_ clause with: _when: pkcsw_output.skipped != True_ which, again, for my case where the previous task is skipped due to, I think, the _pkcs11-switch_ command not existing, fixes the problem. But, this is almost surely not the correct solution.

Any feedback would be greatly appreciated.

Cheers!

**Comment by advocateddrummer** [comment]
All, again, sorry for the noise here, and I wonder if I shouldn't perhaps be submitting this issue at the ComplianceAsCode github page?

In any event, I just noticed that the task that makes sure _opensc_ is installed occurs _after_ several tasks that attempt to use it. Is this also a bug? I have tried moving the task that makes sure that _opensc_ is installed to _before_ the tasks that use it, but I'm still having trouble with it.

**Comment by redhatrises** [comment]
@advocateddrummer yes. Please close this issue and create one on the ComplianceAsCode github page.

**Comment by jgwl** [comment]
@advocateddrummer FYI, I believe my upstream PR https://github.com/ComplianceAsCode/content/pull/3762 fixes this issue. v0.1.43 just got released a few hours ago, so hopefully it will update this repo soon. There's a couple other fixes in there that you may want too.

**Comment by redhatrises** [comment]
@advocateddrummer 

> --- am I safe in assuming that this should run as well on CentOS as RHEL proper?

NO. These roles are designed for RHEL. CentOS fails to meet NIST CUI requirements for security patching as well as for security ciphers. 

> Perhaps it should be mentioned that we do not intend to use smart cards with this computer/project.

FYI. All government projects are now requiring 2FA because insecurities around just username/password. Not sure how much longer exceptions will be made.
